environments:
  gocd_images:
    pipelines:
      - gocd_cplusplus_image
pipelines:
  gocd_cplusplus_image:
    group: gocd_images
    label_template: "${gocd_cplusplus_image_git[:8]}"
    locking: off
    materials:
      gocd_cplusplus_image_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/docker-gocd-agent-cplusplus.git
        branch: main
    parameters:
      IMAGE_TAG: ${GO_REVISION_GOCD_CPLUSPLUS_IMAGE_GIT}
      DEFAULT_TAG: latest
      IMAGE: gocd-agent-cplusplus
    template: docker_image